added docker files

diff --git a/scripts/build b/scripts/build
--- a/scripts/build
+++ b/scripts/build
@@ -1,113 +1,95 @@
 #!/bin/bash
 
-# Copyright (C) 2017 Qualitance
-# Licensed under the Apache License, Version 2.0.
+# Copyright (C) 2017-2018 Andrei Pavel, andrei.pavel@cti.pub.ro
+# Licensed under the MIT License
 
-# Fail script if any command fails.
-set -e
+# Get script path and append it to PATH so other scripts are callable.
+SCRIPT_PATH="$(dirname "$(readlink -f "${0}")")"
+PATH="${PATH}:${SCRIPT_PATH}"
 
-# How to use this tool:
-printUsage() {
-  cat <<EOF
-Usage: $(basename "${0}") [options] [\$platform]
-Options:
-  [-d | --debug]                            enables debug mode
-  [-h | --help]                             shows this usage
-  [-f | --fast]                             skip 'go get' commands
-EOF
-}
+# Header
+ARGUMENTS="\
+  [\$architecture]              architecture to build for i.e. 'arm',
+                               'windows', otherwise build natively
+"
+. header
 
 # Parse arguments.
-fast=false
-while [[ ${#} -ge 1 ]]; do
-  # Debug mode
-  if [[ "${1}" == "-d" || "${1}" == "--debug" ]]; then
-    shift
-    set -x
-    continue
-  fi
-  # Help: display usage
-  if [[ "${1}" == "-h" || "${1}" == "--help" ]]; then
-    shift
-    printUsage
-    exit 0
-  fi
-  # Fast: skip 'go get' commands
-  if [[ "${1}" == "-f" || "${1}" == "--fast" ]]; then
-    shift
-    fast=true
-    continue
-  fi
-  # Platform: linux / mac / windows
-  if [[ -z ${platform} ]]; then
-    platform=${1}
-    shift
-    continue
-  fi
-  # Unrecognized argument.
-  printf "\e[1m\e[31mERROR: Unrecognized argument %s.\e[0m\e[0m\n" "${1}" >&2
-  printUsage
-  exit 1
+while (( ${#} > 0 )); do
+  case "${1}" in
+  *)
+    # architecture i.e. arm, windows
+    [[ -z ${architecture} ]] && architecture="${1}" && shift && continue
+    # Unrecognized argument
+    printf "${RED}ERROR: Unrecognized argument '%s'${RESET}\\n" "${1}" 1>&2; printUsage; exit 1 ;;
+  esac; shift
 done
 
-if [[ ${platform} == "linux" ]]; then
-  printf "%s\n" "Building for Linux..."
-elif [[ ${platform} == "windows" ]]; then
-  printf "%s\n" "Building for Windows..."
-else
-  if [[ ! -z ${platform} ]]; then
-    printf "${RED}%s${STOP}\n" "ERROR: Unrecognized platform ${platform}."
-    exit 2
+function build() {
+  if [[ ${architecture} == "arm" ]]; then
+    printf '%s\n' "Building for Linux ARM..."
+    env GOOS=linux GOARCH=arm GOARM=6 go build -v
+  elif [[ ${architecture} == "windows" ]]; then
+    printf '%s\n' "Building for Windows..."
+    env GOOS=windows GOARCH=amd64 go build -v
+  else
+    printf '%s\n' "Building..."
+    go build -v
   fi
-  printf "%s\n" "Building..."
-fi
+  return ${?}
+}
 
-script_path="$(dirname "$(readlink -f "${0}")")"
-pushd "${script_path}" 1> /dev/null
+function import_dependencies() {
+  pids=()
+  for repository in $(printf '%s' "${repositories}"); do
+    printf '%s\n' "Getting ${repository}..."
+    go get -u "${repository}/..." # & pids+=(${!})
+  done
+  for pid in "${pids[@]}"; do
+    wait "${pid}"
+  done
+  go clean -r
+}
+
+# Get toplevel path.
+pushd "${SCRIPT_PATH}" 1> /dev/null
 {
-GOPATH=$(git rev-parse --show-toplevel)
+  GOPATH=$(git rev-parse --show-toplevel)
 }
 popd 1> /dev/null
-GOBIN=${GOPATH}/bin
 
+# Export Go variables.
+GOBIN=${GOPATH}/bin
 export GOPATH
 export GOBIN
 
-repositories=$(cat <<EOF
-github.com/labstack/echo/...
-github.com/leesper/couchdb-golang/...
+# Define repositories to import.
+repositories="$(cat <<EOF
+github.com/go-yaml/yaml
 EOF
-)
+)"
 
 pushd "${GOPATH}" 1> /dev/null
 {
-  if ! ${fast}; then
-    pids=()
-    for repository in ${repositories}; do
-      go get -u ${repository} & pids+=(${!})
-    done
-    for pid in ${pids[@]}; do
-      wait ${pid}
-    done
-    go clean -r
-  fi
-
-  if [[ ${platform} == "linux" ]]; then
-    env GOOS=linux go build -v
-  elif [[ ${platform} == "windows" ]]; then
-    env GOOS=windows GOARCH=amd64 go build -v
-  else
-    go build -v
-  fi
+  # Build.
+  build
   result=${?}
+
+  if (( result != 0 )); then
+    # Import all repositories asynchronously.
+    import_dependencies
+
+    # Build again.
+    build
+    result=${?}
+  fi
 }
 popd 1> /dev/null
 
-# shellcheck disable=SC2181
-if [[ ${result} -eq 0 ]]; then
-  printf "\nDone.\n"
+# Print result.
+if (( result == 0 )); then
+  printf '\nDone.\n'
 else
-  printf "\nErrors were encountered.\n"
+  printf '\nErrors were encountered.\n'
   exit 3
 fi
-
diff --git a/scripts/install b/scripts/install
--- a/scripts/install
+++ b/scripts/install
@@ -1,49 +1,37 @@
 #!/bin/bash
 
-# Copyright (C) 2017 Qualitance
-# Licensed under the Apache License, Version 2.0.
+# Copyright (C) 2017-2018 Andrei Pavel, andrei.pavel@cti.pub.ro
+# Licensed under the MIT License
 
-# Fail script if any command fails.
-set -e
+# Get script path and append it to PATH so other scripts are callable.
+SCRIPT_PATH="$(dirname "$(readlink -f "${0}")")"
+PATH="${PATH}:${SCRIPT_PATH}"
 
-# How to use this tool:
-printUsage() {
-  cat <<EOF
-Usage: $(basename "${0}") [options]
-Options:
-  [-d | --debug]                            enables debug mode
-  [-h | --help]                             shows this usage
-EOF
-}
+# Header
+ARGUMENTS="\
+"
+. header
 
 # Parse arguments.
-while [[ ${#} -ge 1 ]]; do
-  # Debug mode
-  if [[ "${1}" == "-d" || "${1}" == "--debug" ]]; then
-    shift
-    set -x
-    continue
-  fi
-  # Help: display usage
-  if [[ "${1}" == "-h" || "${1}" == "--help" ]]; then
-    shift
-    printUsage
-    exit 0
-  fi
-  # Unrecognized argument.
-  printf "\e[1m\e[31mERROR: Unrecognized argument %s.\e[0m\e[0m\n" "${1}" >&2
-  printUsage
-  exit 1
+while (( ${#} > 0 )); do
+  case "${1}" in
+  *)
+    # Unrecognized argument
+    printf "${RED}ERROR: Unrecognized argument '%s'${RESET}\\n" "${1}" 1>&2; printUsage; exit 1 ;;
+  esac; shift
 done
 
-script_path="$(dirname "$(readlink -f "${0}")")"
-pushd "${script_path}" 1> /dev/null
+mandatory fast platform
+
+# Get toplevel path.
+pushd "${SCRIPT_PATH}" 1> /dev/null
 {
-GOPATH=$(git rev-parse --show-toplevel)
+  GOPATH=$(git rev-parse --show-toplevel)
 }
 popd 1> /dev/null
-GOBIN=${GOPATH}/bin
 
+# Export Go variables.
+GOBIN=${GOPATH}/bin
 export GOPATH
 export GOBIN
 
@@ -54,11 +42,10 @@ pushd "${GOPATH}" 1> /dev/null
 }
 popd 1> /dev/null
 
-# shellcheck disable=SC2181
-if [[ ${result} -eq 0 ]]; then
+# Print result.
+if (( result == 0 )); then
   printf "\nDone.\n"
 else
   printf "\nErrors were encountered.\n"
   exit 3
 fi
-
