function renames in scripts (minor change)

diff --git a/scripts/build b/scripts/build
--- a/scripts/build
+++ b/scripts/build
@@ -20,31 +20,31 @@ while (( ${#} > 0 )); do
     #                              'windows', otherwise build natively
     [[ -z "${architecture+x}" ]] && architecture="${1}" && shift && continue
     # Unrecognized argument
-    printf "${RED}ERROR: Unrecognized argument '%s'${RESET}\\n" "${1}" 1>&2; printUsage; exit 1 ;;
+    printf "${RED}ERROR: Unrecognized argument '%s'${RESET}\\n" "${1}" 1>&2; print-usage; exit 1 ;;
   esac; shift
 done
 
 function build() {
   if [[ -z "${architecture+x}" ]]; then
-    start_spinner 'Building...'
+    start-spinner 'Building...'
     go build -v
   elif [[ ${architecture} == "arm" ]]; then
-    start_spinner 'Building for Linux ARM...'
+    start-spinner 'Building for Linux ARM...'
     env GOOS=linux GOARCH=arm GOARM=6 go build -v
   elif [[ ${architecture} == "windows" ]]; then
-    start_spinner 'Building for Windows...'
+    start-spinner 'Building for Windows...'
     env GOOS=windows GOARCH=amd64 go build -v
   fi
-  stop_spinner ${?}
+  stop-spinner ${?}
 }
 
 function import_dependencies() {
   pids=()
   for repository in $(printf '%s' "${repositories}"); do
     if [[ ! -d "src/${repository}" ]]; then
-      start_spinner "Getting ${repository}..."
+      start-spinner "Getting ${repository}..."
       go get -u "${repository}/..." # & pids+=(${!})
-      stop_spinner "${?}"
+      stop-spinner "${?}"
     fi
   done
   for pid in "${pids[@]}"; do
diff --git a/scripts/doc b/scripts/doc
--- a/scripts/doc
+++ b/scripts/doc
@@ -15,14 +15,14 @@ while (( ${#} > 0 )); do
   case "${1}" in
   *)
     # Unrecognized argument
-    printf "${RED}ERROR: Unrecognized argument '%s'${RESET}\\n" "${1}" 1>&2; printUsage; exit 1 ;;
+    printf "${RED}ERROR: Unrecognized argument '%s'${RESET}\\n" "${1}" 1>&2; print-usage; exit 1 ;;
   esac; shift
 done
 
 if ! command -v godoc 1> /dev/null; then
-  start_spinner 'Retrieving godoc...'
+  start-spinner 'Retrieving godoc...'
   go get -u golang.org/x/tools/cmd/godoc
-  stop_spinner ${?}
+  stop-spinner ${?}
 fi
 
 # Get toplevel path.
@@ -34,9 +34,9 @@ popd 1> /dev/null
 
 pushd "${toplevel}" 1> /dev/null
 {
-  start_spinner 'Generating documentation...'
+  start-spinner 'Generating documentation...'
   godoc -play -timestamps -v -http=:6060
-  stop_spinner ${?}
+  stop-spinner ${?}
 }
 popd 1> /dev/null
 
diff --git a/scripts/fmt b/scripts/fmt
--- a/scripts/fmt
+++ b/scripts/fmt
@@ -15,7 +15,7 @@ while (( ${#} > 0 )); do
   case "${1}" in
   *)
     # Unrecognized argument
-    printf "${RED}ERROR: Unrecognized argument '%s'${RESET}\\n" "${1}" 1>&2; printUsage; exit 1
+    printf "${RED}ERROR: Unrecognized argument '%s'${RESET}\\n" "${1}" 1>&2; print-usage; exit 1
   esac; shift
 done
 
@@ -24,7 +24,7 @@ done
 
 tmp="$(mktemp -u)"
 
-start_spinner 'Formatting...'
+start-spinner 'Formatting...'
 pushd "${GOPATH}" 1> /dev/null
 {
   files=$(find . -type f -name "*.go")
@@ -39,4 +39,4 @@ pushd "${GOPATH}" 1> /dev/null
   done
 }
 popd 1> /dev/null
-stop_spinner 0
+stop-spinner 0
diff --git a/scripts/install b/scripts/install
--- a/scripts/install
+++ b/scripts/install
@@ -15,7 +15,7 @@ while (( ${#} > 0 )); do
   case "${1}" in
   *)
     # Unrecognized argument
-    printf "${RED}ERROR: Unrecognized argument '%s'${RESET}\\n" "${1}" 1>&2; printUsage; exit 1 ;;
+    printf "${RED}ERROR: Unrecognized argument '%s'${RESET}\\n" "${1}" 1>&2; print-usage; exit 1 ;;
   esac; shift
 done
 
@@ -24,8 +24,8 @@ done
 
 pushd "${GOPATH}" 1> /dev/null
 {
-  start_spinner 'Installing...'
+  start-spinner 'Installing...'
   go install -v
-  stop_spinner ${?}
+  stop-spinner ${?}
 }
 popd 1> /dev/null
diff --git a/scripts/lint b/scripts/lint
--- a/scripts/lint
+++ b/scripts/lint
@@ -15,7 +15,7 @@ while (( ${#} > 0 )); do
   case "${1}" in
   *)
     # Unrecognized argument
-    printf "${RED}ERROR: Unrecognized argument '%s'${RESET}\\n" "${1}" 1>&2; printUsage; exit 1
+    printf "${RED}ERROR: Unrecognized argument '%s'${RESET}\\n" "${1}" 1>&2; print-usage; exit 1
   esac; shift
 done
 
@@ -32,7 +32,7 @@ fi
 # Lint recursively.
 pushd "${GOPATH}" 1> /dev/null
 {
-  start_spinner 'Linting...'
+  start-spinner 'Linting...'
   directories=$(find src -mindepth 1 -maxdepth 1 -type d | sort -V)
   files=$(find . -maxdepth 1 -type f -name "*.go")
   recursive_directories=
@@ -45,6 +45,6 @@ pushd "${GOPATH}" 1> /dev/null
     recursive_directories+="${directory}/... "
   done
   gometalinter ${recursive_directories} ${files} | sort -V
-  stop_spinner ${?}
+  stop-spinner ${?}
 }
 popd 1> /dev/null
